[package]
name = "php-sys"
description = "Rust bindings to PHP's C API."
keywords = ["php", "binding", "bindings", "c", "sys"]
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.68.1"
cc = "1.0.83"
